server.port=8080
spring.application.name=demo-login
max_login_fail=5

data.file.path=D:/demologin/dem_login/dem_login/data/users.json
data.customer.file.path=D:/demologin/dem_login/dem_login/data/customer.json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phanhiu1806@gmail.com
spring.mail.password=chxm okwx qpqy jbgh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.login-url=http://localhost:8080

spring.web.resources.static-locations=classpath:/static/,/

spring.datasource.url=jdbc:sqlserver://DESKTOP-SUGSOJP;port=1433;databaseName=demo_login_db;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_nationalized_character_data=true

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

gemini.api.key=AIzaSyAvD7CHuuXAqmZPr08c8YrNmcRNTr85VBc
